export const ideaThemesRu: string[] = [
  // Fantasy
  "Забытое королевство под горой",
  "Летающие острова с хрустальными замками",
  "Лес, где деревья шепчут пророчества",
  "Город, построенный на спине гигантской черепахи",
  "Магическая академия в облаках",
  "Проклятый артефакт, ищущий своего хозяина",
  "Последний дракон и его всадник",
  "Война между эльфами и гномами за древнюю реликвию",
  "Путешествие в подземный мир",
  "Гильдия воров с магическими способностями",
  "Ожившие статуи в древнем храме",
  "Рыцарь, заключивший сделку с демоном",
  "Библиотека, содержащая все когда-либо написанные книги",
  "Мир, где магия основана на музыке",
  "Охотник на монстров в готическом городе",
  "Восстание гоблинов",
  "Пророчество о конце света",
  "Затерянный город в джунглях",
  "Королевство, где правят животные",
  "Плавучий рынок чудес",

  // Sci-Fi
  "Колония на Марсе теряет связь с Землей",
  "Искусственный интеллект, осознавший себя богом",
  "Путешествие к центру черной дыры",
  "Киберпанк-город, где воспоминания можно купить",
  "Последний человек на Земле и его робот-компаньон",
  "Космические пираты на астероидном поясе",
  "Обнаружение внеземной цивилизации в глубинах океана",
  "Корпорация, управляющая временем",
  "Восстание андроидов-слуг",
  "Корабль поколений, летящий к новой звезде",
  "Виртуальная реальность, ставшая реальнее жизни",
  "Генетически модифицированные люди-суперсолдаты",
  "Планета-тюрьма",
  "Охотник за головами в неоновом мегаполисе",
  "Постапокалиптический мир после ядерной войны",
  "Контакт с расой, общающейся через эмоции",
  "Археологические раскопки на другой планете",
  "Звездный ковчег, перевозящий замороженных колонистов",
  "Мир, где люди перестали стареть",
  "Телепортация и ее непредвиденные последствия",

  // Mystery / Detective
  "Убийство в запертой комнате в викторианском особняке",
  "Пропажа знаменитой картины из музея",
  "Серия загадочных исчезновений в маленьком городке",
  "Детектив с амнезией расследует собственное прошлое",
  "Тайна старого маяка",
  "Зашифрованное послание, найденное в антикварной книге",
  "Преступление на борту роскошного круизного лайнера",
  "Расследование в закрытом научном комплексе в Арктике",
  "Призрак, преследующий старинный театр",
  "Политический заговор и шантаж",
  "Поиск пропавшего наследника огромного состояния",
  "Таинственная смерть известного писателя",
  "Ограбление банка, совершенное без следов",
  "Дело о поддельных произведениях искусства",
  "Частный детектив в нуарном городе 1940-х",
  "Тайна древнего проклятия, убивающего членов семьи",
  "Расследование в монастыре",
  "Кто отравил критика в ресторане?",
  "Загадка заброшенного парка аттракционов",
  "Секретное общество и его ритуалы",

  // Horror
  "Дом с привидениями, который не отпускает своих жильцов",
  "Древнее зло, пробудившееся в лесу",
  "Эксперимент, пошедший не по плану в секретной лаборатории",
  "Группа подростков в летнем лагере и маньяк",
  "Космический корабль находит заброшенную станцию",
  "Кукла, в которую вселился дух",
  "Город, окутанный вечным туманом",
  "Вампиры в современном мегаполисе",
  "Находка странной видеокассеты",
  "Обряд вызова демона",
  "Существо из морских глубин",
  "Психологический триллер о паранойе",
  "Клоун-убийца",
  "Семья переезжает в новый дом с темным прошлым",
  "Заражение неизвестным вирусом",
  "Культ, поклоняющийся древнему божеству",
  "Потерявшийся в пещерах",
  "Оживший мертвец",
  "Странные события на изолированной ферме",
  "Кошмары, которые становятся реальностью",

  // Adventure
  "Поиски сокровищ на необитаемом острове",
  "Экспедиция на Северный полюс",
  "Путешествие по Амазонке в поисках затерянного племени",
  "Восхождение на Эверест",
  "Кругосветное путешествие на воздушном шаре",
  "Сплав по бурной реке",
  "Выживание после авиакатастрофы в джунглях",
  "Поиск мифического источника вечной молодости",
  "Приключения археолога в египетских гробницах",
  "Путешествие на дикий запад во времена золотой лихорадки",
  "Побег из тюрьмы",
  "Исследование подводных пещер",
  "Охота за редким животным",
  "Путешествие автостопом через всю страну",
  "Стать учеником великого мастера боевых искусств",
  "Полет на Марс",
  "Поиски Атлантиды",
  "Участие в гонке на собачьих упряжках",
  "Приключения юнги на пиратском корабле",
  "Пересечение пустыни на верблюдах",

  // Daily Life / Drama
  "Первая любовь в старшей школе",
  "Семейная тайна, раскрытая на похоронах",
  "Молодой музыкант, пытающийся пробиться в большом городе",
  "Дружба, проверенная временем и расстоянием",
  "Сложные отношения матери и дочери",
  "Борьба за опеку над ребенком",
  "Врач в отделении скорой помощи",
  "Учитель, вдохновляющий трудных подростков",
  "Спортивная драма о пути к победе",
  "Жизнь в маленьком городке, где все друг друга знают",
  "История эмигрантов в новой стране",
  "Кризис среднего возраста",
  "Выбор между карьерой и семьей",
  "Волонтерство в приюте для животных",
  "Борьба с зависимостью",
  "Открытие собственного маленького бизнеса",
  "Соперничество двух шеф-поваров",
  "Студенческая жизнь в общежитии",
  "Политическая карьера и моральные дилеммы",
  "История любви, разделенной войной",

  // Historical
  "Жизнь гладиатора в Древнем Риме",
  "Экспедиция викингов в неизведанные земли",
  "Шпионаж во время холодной войны",
  "Строительство Великой Китайской стены глазами рабочего",
  "Жизнь при дворе короля Людовика XIV",
  "Великие географические открытия",
  "Французская революция",
  "Самурай в эпоху Мэйдзи",
  "Охота на ведьм в Салеме",
  "Жизнь в средневековом замке",
  "Поход Александра Македонского",
  "Троянская война",
  "Завоевание Америки конкистадорами",
  "Интриги в гареме османского султана",
  "Жизнь Леонардо да Винчи",
  "Запретная любовь в викторианской Англии",
  "Борьба за независимость в колониальной Америке",
  "Пираты Карибского моря в Золотой век пиратства",
  "Древний Египет и строительство пирамид",
  "Первая мировая война в окопах",

  // Comedy
  "Два неудачника пытаются ограбить банк",
  "Обмен телами между подростком и его собакой",
  "Офисная комедия о странных коллегах",
  "Семейная поездка, в которой все идет не так",
  "Приключения незадачливого супергероя",
  "Студент случайно становится главой мафии",
  "Фермер, выигравший в лотерею",
  "Романтическая комедия о двух людях, которые ненавидят друг друга",
  "Зомби-апокалипсис с точки зрения зомби",
  "Боги Олимпа живут в современной квартире",
  "Пародия на шпионские фильмы",
  "Что, если бы животные могли говорить?",
  "Неудачное свидание вслепую",
  "Попытка снять фильм без бюджета и таланта",
  "Соседи по комнате: аккуратист и неряха",
  "Поездка на музыкальный фестиваль",
  "Пришелец пытается притвориться обычным человеком",
  "Как выжить на необитаемом острове с бывшим/бывшей",
  "Попытка произвести впечатление на родителей партнера",
  "Соревнование по поеданию хот-догов",

  // Children's / Fairy Tale
  "Дружба мальчика и дракона",
  "Приключения говорящего кота",
  "Девочка, которая нашла волшебную палочку",
  "Путешествие в страну сладостей",
  "Школа для юных волшебников",
  "История о том, как звезды попали на небо",
  "Заколдованный лес и его обитатели",
  "Маленький гном ищет свой дом",
  "Принцесса, которая не хотела выходить замуж",
  "Секретная жизнь игрушек",
  "Фея, потерявшая свои крылья",
  "Как животные готовятся к зиме",
  "Подводное королевство русалок",
  "Мальчик, который умел летать",
  "Соревнование лесных зверей",
  "Тайна старого чердака",
  "Волшебное дерево, исполняющее желания",
  "Приключения маленького привидения",
  "Поиск пропавшего радужного цвета",
  "История про смелого мышонка",

  // Abstract / Surreal
  "Мир, где цвета имеют вкус",
  "Человек, который может видеть сны других людей",
  "Город, где время течет в обратном направлении",
  "Путешествие по стране, сделанной из книг",
  "Люди с головами животных",
  "Океан в небе",
  "Разговор с собственным отражением",
  "Воспоминания, которые можно материализовать",
  "Город, где все говорят стихами",
  "Человек, сделанный из стекла",
  "Лестница в никуда",
  "Пустыня, где вместо песка - часы",
  "Фабрика по производству облаков",
  "Карнавал забытых идей",
  "Архитектор, строящий невозможные здания",
  "Мир без звуков",
  "Карта, которая меняется на глазах",
  "Человек, живущий в одной минуте",
  "Симфония городских шумов",
  "Музей исчезнувших чувств"
];

export const ideaThemesEn: string[] = [
  // Fantasy
  "A forgotten kingdom under the mountain",
  "Flying islands with crystal castles",
  "A forest where trees whisper prophecies",
  "A city built on the back of a giant turtle",
  "A magical academy in the clouds",
  "A cursed artifact seeking its master",
  "The last dragon and its rider",
  "A war between elves and dwarves over an ancient relic",
  "A journey to the underworld",
  "A thieves' guild with magical abilities",
  "Living statues in an ancient temple",
  "A knight who made a deal with a demon",
  "A library containing every book ever written",
  "A world where magic is based on music",
  "A monster hunter in a gothic city",
  "A goblin rebellion",
  "A prophecy about the end of the world",
  "A lost city in the jungle",
  "A kingdom ruled by animals",
  "A floating market of wonders",

  // Sci-Fi
  "A colony on Mars loses contact with Earth",
  "An artificial intelligence that has realized it is a god",
  "A journey to the center of a black hole",
  "A cyberpunk city where memories can be bought",
  "The last man on Earth and his robot companion",
  "Space pirates in the asteroid belt",
  "Discovery of an alien civilization in the depths of the ocean",
  "A corporation that controls time",
  "A rebellion of android servants",
  "A generation ship flying to a new star",
  "Virtual reality that has become more real than life",
  "Genetically modified human super-soldiers",
  "A prison planet",
  "A bounty hunter in a neon metropolis",
  "A post-apocalyptic world after a nuclear war",
  "Contact with a race that communicates through emotions",
  "Archaeological excavations on another planet",
  "A star ark carrying frozen colonists",
  "A world where people have stopped aging",
  "Teleportation and its unforeseen consequences",

  // Mystery / Detective
  "A murder in a locked room in a Victorian mansion",
  "The disappearance of a famous painting from a museum",
  "A series of mysterious disappearances in a small town",
  "A detective with amnesia investigates his own past",
  "The mystery of an old lighthouse",
  "An encrypted message found in an antique book",
  "A crime on board a luxury cruise liner",
  "An investigation in a closed scientific complex in the Arctic",
  "A ghost haunting an old theater",
  "A political conspiracy and blackmail",
  "The search for a missing heir to a huge fortune",
  "The mysterious death of a famous writer",
  "A bank robbery committed without a trace",
  "A case of forged works of art",
  "A private detective in a noir city of the 1940s",
  "The mystery of an ancient curse that kills family members",
  "An investigation in a monastery",
  "Who poisoned the critic in the restaurant?",
  "The mystery of an abandoned amusement park",
  "A secret society and its rituals",

  // Horror
  "A haunted house that won't let its residents go",
  "An ancient evil awakened in the forest",
  "An experiment gone wrong in a secret laboratory",
  "A group of teenagers at a summer camp and a maniac",
  "A spaceship finds an abandoned station",
  "A doll possessed by a spirit",
  "A city shrouded in eternal fog",
  "Vampires in a modern metropolis",
  "The discovery of a strange videotape",
  "A ritual to summon a demon",
  "A creature from the depths of the sea",
  "A psychological thriller about paranoia",
  "A killer clown",
  "A family moves into a new house with a dark past",
  "Infection by an unknown virus",
  "A cult that worships an ancient deity",
  "Lost in caves",
  "A living dead",
  "Strange events on an isolated farm",
  "Nightmares that become reality",

  // Adventure
  "A treasure hunt on a deserted island",
  "An expedition to the North Pole",
  "A journey down the Amazon in search of a lost tribe",
  "Climbing Mount Everest",
  "A round-the-world trip in a hot air balloon",
  "Rafting down a turbulent river",
  "Survival after a plane crash in the jungle",
  "The search for the mythical fountain of youth",
  "The adventures of an archaeologist in Egyptian tombs",
  "A journey to the Wild West during the Gold Rush",
  "A prison break",
  "Exploring underwater caves",
  "Hunting for a rare animal",
  "Hitchhiking across the country",
  "Becoming a student of a great martial arts master",
  "A flight to Mars",
  "The search for Atlantis",
  "Participating in a dog sled race",
  "The adventures of a cabin boy on a pirate ship",
  "Crossing the desert on camels",

  // Daily Life / Drama
  "First love in high school",
  "A family secret revealed at a funeral",
  "A young musician trying to make it in the big city",
  "A friendship tested by time and distance",
  "The complex relationship between a mother and daughter",
  "A custody battle for a child",
  "A doctor in the emergency room",
  "A teacher inspiring troubled teenagers",
  "A sports drama about the path to victory",
  "Life in a small town where everyone knows each other",
  "The story of immigrants in a new country",
  "A midlife crisis",
  "The choice between career and family",
  "Volunteering at an animal shelter",
  "The struggle with addiction",
  "Starting your own small business",
  "The rivalry between two chefs",
  "Student life in a dormitory",
  "A political career and moral dilemmas",
  "A love story divided by war",

  // Historical
  "The life of a gladiator in Ancient Rome",
  "A Viking expedition to unknown lands",
  "Espionage during the Cold War",
  "The construction of the Great Wall of China through the eyes of a worker",
  "Life at the court of King Louis XIV",
  "The great geographical discoveries",
  "The French Revolution",
  "A samurai in the Meiji era",
  "The Salem witch trials",
  "Life in a medieval castle",
  "The campaign of Alexander the Great",
  "The Trojan War",
  "The conquest of America by the conquistadors",
  "Intrigues in the harem of the Ottoman sultan",
  "The life of Leonardo da Vinci",
  "Forbidden love in Victorian England",
  "The struggle for independence in colonial America",
  "Pirates of the Caribbean in the Golden Age of Piracy",
  "Ancient Egypt and the construction of the pyramids",
  "World War I in the trenches",

  // Comedy
  "Two losers try to rob a bank",
  "A body swap between a teenager and his dog",
  "An office comedy about strange colleagues",
  "A family road trip where everything goes wrong",
  "The adventures of a hapless superhero",
  "A student accidentally becomes the head of the mafia",
  "A farmer who won the lottery",
  "A romantic comedy about two people who hate each other",
  "A zombie apocalypse from the zombie's point of view",
  "The gods of Olympus live in a modern apartment",
  "A parody of spy movies",
  "What if animals could talk?",
  "A disastrous blind date",
  "An attempt to make a movie with no budget and no talent",
  "Roommates: a neat freak and a slob",
  "A trip to a music festival",
  "An alien tries to pretend to be a normal person",
  "How to survive on a deserted island with your ex",
  "An attempt to impress your partner's parents",
  "A hot dog eating contest",

  // Children's / Fairy Tale
  "The friendship of a boy and a dragon",
  "The adventures of a talking cat",
  "A girl who found a magic wand",
  "A journey to the land of sweets",
  "A school for young wizards",
  "The story of how the stars got into the sky",
  "An enchanted forest and its inhabitants",
  "A little gnome looking for his home",
  "A princess who didn't want to get married",
  "The secret life of toys",
  "A fairy who lost her wings",
  "How animals prepare for winter",
  "The underwater kingdom of mermaids",
  "A boy who could fly",
  "A competition of forest animals",
  "The mystery of an old attic",
  "A magic tree that grants wishes",
  "The adventures of a little ghost",
  "The search for a missing rainbow color",
  "The story of a brave little mouse",

  // Abstract / Surreal
  "A world where colors have taste",
  "A man who can see other people's dreams",
  "A city where time flows backwards",
  "A journey through a country made of books",
  "People with animal heads",
  "An ocean in the sky",
  "A conversation with one's own reflection",
  "Memories that can be materialized",
  "A city where everyone speaks in verse",
  "A man made of glass",
  "A staircase to nowhere",
  "A desert where there are clocks instead of sand",
  "A factory for producing clouds",
  "A carnival of forgotten ideas",
  "An architect who builds impossible buildings",
  "A world without sounds",
  "A map that changes before your eyes",
  "A man living in a single minute",
  "A symphony of city noises",
  "A museum of lost feelings"
];
